name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Déclencher le workflow sur les pushes vers la branche master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Load .env file
      #   run: |
      #     set -a
      #     source .env
      #     set +a
      #     echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Update JWT Secret in application.properties
        run: sed -i 's/${JWT_SECRET}/${{ secrets.JWT_SECRET }}/' src/main/resources/application.properties
      
      - name: Update DB_HOST in application.properties, to database service name in docker-compose (db)
        run: sed -i 's/${DB_HOST}/db/' src/main/resources/application.properties
      
      - name: Build with Maven
        run: mvn clean package
      
      - name: Extract version from pom.xml
        id: extract_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Obtenir le nom du dépôt
        id: get_repo_name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.VERSION }}